### PR TITLE
Pull request for review Milestone: friendships v1 

### PR DESCRIPTION
**Pull request by visva-dev**
# Milestone: friendships v1 
- Add friendships model
- Associations to user and friendship tables

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @visva-dev and @eypsrcnuygr 
### You have done well so far, however, you have a few issues to fix:-
- [x] Add a function where a user can invite friends
- [x] User can see friendships requests from friends
- [x] User has to accept friendship request to start friendship
- [x] User can reject a friendship request
- [x] There is a button to invite user to friendship on users list page and on single user page
- [ ] Posts timeline includes posts written by logged-in user and their friends
- [ ] Remove the stickler file as we no longer use it, rather we use git hub actions
- [ ] Do not change rubocop setting by Microverse, for reference [use this link](https://github.com/microverseinc/linters-config/tree/master/ror) and solve the below error
`Error: unrecognized cop Lint/RaiseException found in .rubocop.yml, unrecognized cop Lint/StructNewOverride found in .rubocop.yml`
### Add these features and submit for another code review. Good luck!
- Happy coding!

By Raymond
Slack @iamraymond

**Comment by eypsrcnuygr** [comment]
- We did not add any stickler since we haven't created repo but we've forked it.
- We did not change any rubocop configuration since we haven't created repo but we've forked it.

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Well done working on the suggested changes from the last review. However, there is one change that you need to make before moving forward;
- [ ] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Your current app version displays all posts to the logged-in user.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by eypsrcnuygr** [comment]
- At the index page you just see the friends' and user's own posts.

**Review by mosesogwo — APPROVED** [review]
**Well done :+1: Your milestone looks okay!**

- You will be shown a simpler way to retrieve timeline posts in the next milestone.

_**Good luck:stars:**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
